# Generated by Django 5.1.1 on 2024-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images/%y/%m/&=%d'),
        ),
    ]
